name: De4js
description: JavaScript Deobfuscator and Unpacker
version: 1.3.0
author: tunganhken
author_email: tunganhken@gmail.com
url: https://tunganhken.github.io
baseurl: /de4js
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-106940288-1
sass:
  style: compressed

exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'package-lock.json']
